version: "3.8"
services:
    app:
        container_name: app
        restart: always
        build: .
        ports: 
            - "3000:3000"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: centos/mongodb-32-centos7
        ports: 
            - "20117:27017"